import type { ArtProps } from "../props"

// Ported from business.x.com — basics/intro-x-for-business · Reach new audiences; spotlight-takeovers.
export function AudienceCloud(props: ArtProps) {
  return (
    <svg
      viewBox="-6 -6 84 84"
      fill="none"
      shapeRendering="geometricPrecision"
      aria-hidden="true"
      {...props}
    >
      <g data-group="rays">
        <line
          data-part="ray"
          data-pos="ne"
          x1="36.55"
          y1="36.25"
          x2="59.25"
          y2="12.25"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="3.2 3.2"
        />
        <line
          data-part="ray"
          data-pos="nw"
          x1="36.55"
          y1="36.25"
          x2="13.25"
          y2="12.25"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="3.2 3.2"
        />
        <line
          data-part="ray"
          data-pos="w-lower"
          x1="36.55"
          y1="36.25"
          x2="2.25"
          y2="47.45"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="3.2 3.2"
        />
        <line
          data-part="ray"
          data-pos="e-upper"
          x1="36.55"
          y1="36.25"
          x2="70.25"
          y2="24.85"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="3.2 3.2"
        />
        <line
          data-part="ray"
          data-pos="sw"
          x1="36.55"
          y1="36.25"
          x2="13.25"
          y2="58.25"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="3.2 3.2"
        />
        <line
          data-part="ray"
          data-pos="s-right"
          x1="36.55"
          y1="36.25"
          x2="47.25"
          y2="70.25"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="3.2 3.2"
        />
      </g>
      <path
        data-part="frame"
        d="M36.55 19.28L53.519999999999996 36.25L36.55 53.22L19.58 36.25Z"
        fill="var(--ds-background-100)"
        stroke="currentColor"
        strokeWidth="0.5"
        strokeDasharray="3.2 3.2"
      />
      <circle data-part="hub" cx="36.55" cy="36.25" r="2" fill="currentColor" />
      <g data-group="nodes">
        <g data-part="node" data-pos="ne">
          <circle
            data-state="hollow"
            cx="59.25"
            cy="12.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="59.25"
            cy="12.25"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0"
          />
        </g>
        <g data-part="node" data-pos="nw">
          <circle
            data-state="hollow"
            cx="13.25"
            cy="12.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="13.25"
            cy="12.25"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0"
          />
        </g>
        <g data-part="node" data-pos="w-lower">
          <circle
            data-state="hollow"
            cx="2.25"
            cy="47.45"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="2.25"
            cy="47.45"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0"
          />
        </g>
        <g data-part="node" data-pos="e-upper">
          <circle
            data-state="hollow"
            cx="70.25"
            cy="24.85"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="70.25"
            cy="24.85"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0.9959183822211344"
          />
        </g>
        <g data-part="node" data-pos="sw">
          <circle
            data-state="hollow"
            cx="13.25"
            cy="58.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="13.25"
            cy="58.25"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0.9959183822211344"
          />
        </g>
        <g data-part="node" data-pos="s-right">
          <circle
            data-state="hollow"
            cx="47.25"
            cy="70.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="47.25"
            cy="70.25"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0.9959183822211344"
          />
        </g>
        <g data-part="node" data-pos="e-lower">
          <circle
            data-state="hollow"
            cx="70.25"
            cy="47.45"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="70.25"
            cy="47.45"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
          />
        </g>
        <g data-part="node" data-pos="w-upper">
          <circle
            data-state="hollow"
            cx="2.25"
            cy="24.85"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="2.25"
            cy="24.85"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
          />
        </g>
        <g data-part="node" data-pos="s-left">
          <circle
            data-state="hollow"
            cx="24.25"
            cy="70.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="24.25"
            cy="70.25"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
          />
        </g>
        <g data-part="node" data-pos="se">
          <circle
            data-state="hollow"
            cx="59.25"
            cy="58.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="59.25"
            cy="58.25"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0.0040816177788656205"
          />
        </g>
        <g data-part="node" data-pos="n-left">
          <circle
            data-state="hollow"
            cx="24.25"
            cy="2.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="24.25"
            cy="2.25"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0.0040816177788656205"
          />
        </g>
        <g data-part="node" data-pos="n-right">
          <circle
            data-state="hollow"
            cx="47.25"
            cy="2.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-state="filled"
            cx="47.25"
            cy="2.25"
            r="2"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
            opacity="0.0040816177788656205"
          />
        </g>
      </g>
    </svg>
  )
}
