import type { ArtProps } from "../props"

// Ported from business.x.com: basics/intro-x-for-business · Experiment with tone; advertising.
export function ToneRows(props: ArtProps) {
  return (
    <svg
      viewBox="-5.75 -5.75 84 84"
      fill="none"
      shapeRendering="geometricPrecision"
      aria-hidden="true"
      {...props}
    >
      <g data-group="conversation-row-1">
        <line
          data-part="connector"
          x1="4.25"
          y1="9.25"
          x2="68.25"
          y2="9.25"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="3.2 3.2"
        />
        <g data-part="marker-square">
          <rect
            x="0.25"
            y="7.25"
            width="4"
            height="4"
            fill="var(--ds-background-100)"
          />
          <rect
            data-part="marker-fill"
            x="0.25"
            y="7.25"
            width="4"
            height="4"
            fill="currentColor"
            style={{ transformBox: "fill-box", transformOrigin: "center" }}
          />
          <rect
            x="0.25"
            y="7.25"
            width="4"
            height="4"
            fill="none"
            stroke="currentColor"
            strokeWidth="0.5"
          />
        </g>
        <g data-part="marker-square">
          <rect
            x="68.25"
            y="7.25"
            width="4"
            height="4"
            fill="var(--ds-background-100)"
          />
          <rect
            data-part="marker-fill"
            x="68.25"
            y="7.25"
            width="4"
            height="4"
            fill="currentColor"
            style={{ transformBox: "fill-box", transformOrigin: "center" }}
            opacity="0"
          />
          <rect
            x="68.25"
            y="7.25"
            width="4"
            height="4"
            fill="none"
            stroke="currentColor"
            strokeWidth="0.5"
          />
        </g>
        <g data-part="carriage">
          <circle
            data-part="ring"
            cx="49.25"
            cy="9.25"
            r="9"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-part="node-idle"
            cx="49.25"
            cy="9.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-part="node-active"
            cx="49.25"
            cy="9.25"
            r="2"
            fill="currentColor"
            opacity="0.816293486423092"
          />
        </g>
      </g>
      <g data-group="conversation-row-2">
        <line
          data-part="connector"
          x1="4.25"
          y1="36.25"
          x2="68.25"
          y2="36.25"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="3.2 3.2"
        />
        <g data-part="marker-square">
          <rect
            x="0.25"
            y="34.25"
            width="4"
            height="4"
            fill="var(--ds-background-100)"
          />
          <rect
            data-part="marker-fill"
            x="0.25"
            y="34.25"
            width="4"
            height="4"
            fill="currentColor"
            style={{ transformBox: "fill-box", transformOrigin: "center" }}
            opacity="0"
          />
          <rect
            x="0.25"
            y="34.25"
            width="4"
            height="4"
            fill="none"
            stroke="currentColor"
            strokeWidth="0.5"
          />
        </g>
        <g data-part="marker-square">
          <rect
            x="68.25"
            y="34.25"
            width="4"
            height="4"
            fill="var(--ds-background-100)"
          />
          <rect
            data-part="marker-fill"
            x="68.25"
            y="34.25"
            width="4"
            height="4"
            fill="currentColor"
            style={{ transformBox: "fill-box", transformOrigin: "center" }}
          />
          <rect
            x="68.25"
            y="34.25"
            width="4"
            height="4"
            fill="none"
            stroke="currentColor"
            strokeWidth="0.5"
          />
        </g>
        <g data-part="carriage">
          <circle
            data-part="ring"
            cx="24.25"
            cy="36.25"
            r="9"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-part="node-idle"
            cx="24.25"
            cy="36.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-part="node-active"
            cx="24.25"
            cy="36.25"
            r="2"
            fill="currentColor"
          />
        </g>
      </g>
      <g data-group="conversation-row-3">
        <line
          data-part="connector"
          x1="4.25"
          y1="63.25"
          x2="68.25"
          y2="63.25"
          stroke="currentColor"
          strokeWidth="0.5"
          strokeDasharray="3.2 3.2"
        />
        <g data-part="marker-square">
          <rect
            x="0.25"
            y="61.25"
            width="4"
            height="4"
            fill="var(--ds-background-100)"
          />
          <rect
            data-part="marker-fill"
            x="0.25"
            y="61.25"
            width="4"
            height="4"
            fill="currentColor"
            style={{ transformBox: "fill-box", transformOrigin: "center" }}
            opacity="0"
          />
          <rect
            x="0.25"
            y="61.25"
            width="4"
            height="4"
            fill="none"
            stroke="currentColor"
            strokeWidth="0.5"
          />
        </g>
        <g data-part="marker-square">
          <rect
            x="68.25"
            y="61.25"
            width="4"
            height="4"
            fill="var(--ds-background-100)"
          />
          <rect
            data-part="marker-fill"
            x="68.25"
            y="61.25"
            width="4"
            height="4"
            fill="currentColor"
            style={{ transformBox: "fill-box", transformOrigin: "center" }}
          />
          <rect
            x="68.25"
            y="61.25"
            width="4"
            height="4"
            fill="none"
            stroke="currentColor"
            strokeWidth="0.5"
          />
        </g>
        <g data-part="carriage">
          <circle
            data-part="ring"
            cx="49.25"
            cy="63.25"
            r="9"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-part="node-idle"
            cx="49.25"
            cy="63.25"
            r="2"
            fill="var(--ds-background-100)"
            stroke="currentColor"
            strokeWidth="0.5"
          />
          <circle
            data-part="node-active"
            cx="49.25"
            cy="63.25"
            r="2"
            fill="currentColor"
            opacity="0"
          />
        </g>
      </g>
    </svg>
  )
}
