// Generates __previews__/index.tsx: the list and dynamic-import map of
// blocks, examples and demos that the playground palette, /preview/[name]
// and the docs' <DemoPreview> load.
//
//   components/blocks/<name>/index.tsx  -> block
//   components/examples/<name>.tsx      -> example
//   components/demos/<name>.tsx         -> demo (inline in a docs page)
//
// App-internal. None of this is published; the registry is components/ui
// only (see scripts/build-registry.ts).

import fs from "node:fs"
import path from "node:path"

const ROOT = process.cwd()
const OUT = path.join(ROOT, "__previews__/index.tsx")

type PreviewEntry = {
  name: string
  title: string
  type: "block" | "example" | "demo"
  entry: string
}

// Names whose derived title reads wrong. Everything else is title-cased with
// the -example suffix dropped.
const TITLE_OVERRIDES: Record<string, string> = {
  "input-otp-example": "Input OTP",
  "preview-02": "Preview 02",
  "preview-03": "Preview 03",
  "sidebar-floating-example": "Sidebar (Floating)",
  "sidebar-icon-example": "Sidebar (Icon)",
  "sidebar-inset-example": "Sidebar (Inset)",
}

function titleFromName(name: string): string {
  return (
    TITLE_OVERRIDES[name] ??
    name
      .replace(/-example$/, "")
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(" ")
  )
}

function collectFiles(dir: string, type: "example" | "demo"): PreviewEntry[] {
  if (!fs.existsSync(dir)) return []
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".tsx"))
    .sort()
    .map<PreviewEntry>((f) => {
      const name = f.replace(/\.tsx$/, "")
      return {
        name,
        title: titleFromName(name),
        type,
        entry: `${path.relative(ROOT, dir)}/${f}`,
      }
    })
}

// Blocks first, then examples — the order /create's action menu shows them.
// Demos follow; the palette does not list them.
function collect(): PreviewEntry[] {
  const blocksDir = path.join(ROOT, "components/blocks")

  const blocks = fs
    .readdirSync(blocksDir, { withFileTypes: true })
    .filter(
      (d) =>
        d.isDirectory() &&
        fs.existsSync(path.join(blocksDir, d.name, "index.tsx"))
    )
    .map((d) => d.name)
    .sort()
    .map<PreviewEntry>((name) => ({
      name,
      title: titleFromName(name),
      type: "block",
      entry: `components/blocks/${name}/index.tsx`,
    }))

  const examples = collectFiles(
    path.join(ROOT, "components/examples"),
    "example"
  )
  const demos = collectFiles(path.join(ROOT, "components/demos"), "demo")

  const names = new Set<string>()
  for (const p of [...blocks, ...examples, ...demos]) {
    if (names.has(p.name)) throw new Error(`previews: duplicate name ${p.name}`)
    names.add(p.name)
  }

  return [...blocks, ...examples, ...demos]
}

const previews = collect()

const loaders = previews
  .map(
    (p) =>
      `  "${p.name}": () => import("@/${p.entry.replace(/(\/index)?\.tsx$/, "")}"),`
  )
  .join("\n")
const items = previews
  .map(
    (p) =>
      `  { name: ${JSON.stringify(p.name)}, title: ${JSON.stringify(p.title)}, type: "${p.type}", entry: ${JSON.stringify(p.entry)} },`
  )
  .join("\n")

const source = `// Generated by scripts/build-previews.ts. Do not edit.
// App-internal blocks, examples and demos for the playground, /preview/[name]
// and the docs' <DemoPreview>.

export type PreviewItem = {
  name: string
  title: string
  type: "block" | "example" | "demo"
  /** Source file, relative to apps/www */
  entry: string
}

export const PREVIEW_ITEMS: PreviewItem[] = [
${items}
]

export const Index: Record<
  string,
  () => Promise<{ default: React.ComponentType }>
> = {
${loaders}
}
`

fs.mkdirSync(path.dirname(OUT), { recursive: true })
fs.writeFileSync(OUT, source)
console.log(
  `previews: ${previews.length} items`,
  previews.reduce<Record<string, number>>((acc, p) => {
    acc[p.type] = (acc[p.type] ?? 0) + 1
    return acc
  }, {})
)
