// Generates __previews__/index.tsx: the list and dynamic-import map of
// blocks and examples that the playground palette and /preview/[name] load.
//
//   components/blocks/<name>/index.tsx  -> block
//   components/examples/<name>.tsx      -> example
//
// App-internal. None of this is published; the registry is components/ui
// only (see scripts/build-registry.ts).

import fs from "node:fs"
import path from "node:path"

const ROOT = process.cwd()
const OUT = path.join(ROOT, "__previews__/index.tsx")

type PreviewEntry = {
  name: string
  title: string
  type: "block" | "example"
  entry: string
}

// Names whose derived title reads wrong. Everything else is title-cased with
// the -example suffix dropped.
const TITLE_OVERRIDES: Record<string, string> = {
  "input-otp-example": "Input OTP",
  "preview-02": "Preview 02",
  "preview-03": "Preview 03",
  "sidebar-floating-example": "Sidebar (Floating)",
  "sidebar-icon-example": "Sidebar (Icon)",
  "sidebar-inset-example": "Sidebar (Inset)",
}

function titleFromName(name: string): string {
  return (
    TITLE_OVERRIDES[name] ??
    name
      .replace(/-example$/, "")
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(" ")
  )
}

// Blocks first, then examples — the order /create's action menu shows them.
function collect(): PreviewEntry[] {
  const blocksDir = path.join(ROOT, "components/blocks")
  const examplesDir = path.join(ROOT, "components/examples")

  const blocks = fs
    .readdirSync(blocksDir, { withFileTypes: true })
    .filter(
      (d) =>
        d.isDirectory() &&
        fs.existsSync(path.join(blocksDir, d.name, "index.tsx"))
    )
    .map((d) => d.name)
    .sort()
    .map<PreviewEntry>((name) => ({
      name,
      title: titleFromName(name),
      type: "block",
      entry: `@/components/blocks/${name}`,
    }))

  const examples = fs
    .readdirSync(examplesDir)
    .filter((f) => f.endsWith(".tsx"))
    .sort()
    .map<PreviewEntry>((f) => {
      const name = f.replace(/\.tsx$/, "")
      return {
        name,
        title: titleFromName(name),
        type: "example",
        entry: `@/components/examples/${name}`,
      }
    })

  return [...blocks, ...examples]
}

const previews = collect()

const loaders = previews
  .map((p) => `  "${p.name}": () => import("${p.entry}"),`)
  .join("\n")
const items = previews
  .map(
    (p) =>
      `  { name: ${JSON.stringify(p.name)}, title: ${JSON.stringify(p.title)}, type: "${p.type}" },`
  )
  .join("\n")

const source = `// Generated by scripts/build-previews.ts. Do not edit.
// App-internal blocks and examples for the playground and /preview/[name].

export type PreviewItem = {
  name: string
  title: string
  type: "block" | "example"
}

export const PREVIEW_ITEMS: PreviewItem[] = [
${items}
]

export const Index: Record<
  string,
  () => Promise<{ default: React.ComponentType }>
> = {
${loaders}
}
`

fs.mkdirSync(path.dirname(OUT), { recursive: true })
fs.writeFileSync(OUT, source)
console.log(
  `previews: ${previews.length} items`,
  previews.reduce<Record<string, number>>((acc, p) => {
    acc[p.type] = (acc[p.type] ?? 0) + 1
    return acc
  }, {})
)
