import type { ArtProps } from "../props"

// Ported from help.x.com: safety-and-security.
export function RelayPair(props: ArtProps) {
  return (
    <svg
      fill="none"
      shapeRendering="geometricPrecision"
      viewBox="0 0 320 224"
      aria-hidden="true"
      {...props}
    >
      <g data-group="lanes" data-pos="bottom">
        <line
          data-part="lane"
          data-pos="bottom-left"
          data-state="solid"
          stroke="currentColor"
          strokeWidth="1"
          x1="73"
          x2="176"
          y1="144.357"
          y2="144.357"
        />
        <line
          data-part="lane"
          data-pos="bottom-right"
          data-state="dashed"
          stroke="currentColor"
          strokeDasharray="4 4"
          strokeWidth="1"
          x1="144"
          x2="247"
          y1="144.357"
          y2="144.357"
        />
      </g>
      <rect
        data-part="panel"
        fill="var(--ds-background-100)"
        height="119"
        stroke="currentColor"
        strokeWidth="1"
        width="55"
        x="132.5"
        y="52.857"
      />
      <g data-group="gate" data-pos="bottom">
        <circle
          cx="160"
          cy="144.357"
          data-part="node"
          fill="var(--ds-background-100)"
          r="19.5"
          stroke="currentColor"
          strokeWidth="1"
        />
        <circle
          cx="160"
          cy="144.357"
          data-part="dot"
          fill="var(--ds-background-100)"
          r="3"
          stroke="currentColor"
          strokeWidth="1"
        />
        <rect
          data-part="terminal"
          data-pos="bottom-left"
          data-state="hollow"
          fill="var(--ds-background-100)"
          height="6"
          stroke="currentColor"
          strokeWidth="1"
          width="6"
          x="70"
          y="141.357"
        />
        <rect
          data-part="terminal"
          data-pos="bottom-right"
          data-state="hollow"
          fill="var(--ds-background-100)"
          height="6"
          stroke="currentColor"
          strokeWidth="1"
          width="6"
          x="244"
          y="141.357"
        />
      </g>
      <g data-group="lanes" data-pos="top">
        <line
          data-part="lane"
          data-pos="top-left"
          data-state="dashed"
          stroke="currentColor"
          strokeDasharray="4 4"
          strokeWidth="1"
          x1="73"
          x2="176"
          y1="80.357"
          y2="80.357"
        />
        <line
          data-part="lane"
          data-pos="top-right"
          data-state="solid"
          stroke="currentColor"
          strokeWidth="1"
          x1="144"
          x2="247"
          y1="80.357"
          y2="80.357"
        />
      </g>
      <g data-group="gate" data-pos="top">
        <circle
          cx="160"
          cy="80.357"
          data-part="node"
          fill="var(--ds-background-100)"
          r="19.5"
          stroke="currentColor"
          strokeWidth="1"
        />
        <circle
          cx="160"
          cy="80.357"
          data-part="dot"
          fill="var(--ds-background-100)"
          r="3"
          stroke="currentColor"
          strokeWidth="1"
        />
        <rect
          data-part="terminal"
          data-pos="top-left"
          data-state="filled"
          fill="currentColor"
          height="6"
          stroke="none"
          strokeWidth="1"
          width="6"
          x="70"
          y="77.357"
        />
        <rect
          data-part="terminal"
          data-pos="top-right"
          data-state="hollow"
          fill="var(--ds-background-100)"
          height="6"
          stroke="currentColor"
          strokeWidth="1"
          width="6"
          x="244"
          y="77.357"
        />
      </g>
    </svg>
  )
}
