// One line per published ui component, for the index and the generic page.
// Names are registry item names. A component without an entry still gets a
// page; it just has no description until one lands here.
export const componentDescriptions: Record<string, string> = {
  accordion: "Vertically stacked sections that expand one at a time.",
  alert: "A short inline message that stays on the page.",
  "alert-dialog":
    "A modal that interrupts for a decision and blocks until it gets one.",
  "aspect-ratio": "Holds content at a fixed width-to-height ratio.",
  attachment: "A file or media chip with a title, description and actions.",
  avatar: "An image for a person or entity, with a fallback.",
  badge: "A small label for a status or a count.",
  breadcrumb: "The path to the current page, one link per level.",
  bubble: "A chat message bubble with grouping and reactions.",
  button:
    "Triggers an action. Six variants on the ramp, four sizes on the Button type roles.",
  "button-group": "Joins adjacent buttons into one control.",
  calendar: "A month grid for picking one date or a range.",
  card: "A flat container for a titled group of content.",
  carousel: "Scrolls a row of items with previous and next controls.",
  chart:
    "Recharts wrappers bound to the chart colors and the tooltip material.",
  checkbox: "A control that toggles between checked and unchecked.",
  collapsible: "Shows and hides a region of content.",
  combobox: "A text input with a filtered list of options.",
  command:
    "A command palette: a search input over grouped, keyboard-driven items.",
  "context-menu": "A menu opened by right click or long press.",
  dialog: "A modal window layered over the page.",
  direction: "Provides the reading direction to every component below it.",
  drawer: "A panel that slides in from the edge of the screen.",
  "dropdown-menu":
    "A menu opened from a trigger, with items, groups and submenus.",
  empty: "A placeholder for a region with nothing in it yet.",
  field: "Label, control, description and error, laid out consistently.",
  "hover-card": "A preview that opens on hover or focus.",
  input: "A single-line text field.",
  "input-group": "An input with addons on either side.",
  "input-otp": "One box per character for one-time codes.",
  item: "A list row with media, title, description and actions.",
  kbd: "A keyboard key or a chord.",
  label: "A caption for a form control.",
  marker: "A small inline status mark with an icon.",
  menubar: "A horizontal bar of menus, as in a desktop app.",
  message: "A chat message with avatar, header, content and footer.",
  "message-scroller":
    "A scroll container for a message stream that follows the newest item.",
  "native-select": "The platform select element, styled onto the ramp.",
  "navigation-menu": "Site navigation with flyout content.",
  pagination: "Links between pages of results.",
  popover: "Rich content anchored to a trigger.",
  progress: "How far a task has come.",
  questionnaire: "A stepped set of single-choice questions with progress.",
  "radio-group": "Pick exactly one of a set.",
  resizable: "Panels with a draggable handle between them.",
  "scroll-area": "A scroll container with a themed scrollbar.",
  select: "Pick one of a list of options.",
  separator: "A visual divider.",
  sheet: "A dialog that opens from the side of the screen.",
  sidebar: "A collapsible application sidebar with groups, menus and rail.",
  skeleton: "A placeholder shape while content loads.",
  slider: "Pick a value or a range along a track.",
  sonner: "Stacked toast notifications.",
  spinner: "An indeterminate loading indicator.",
  switch: "A control that toggles between on and off.",
  table: "Rows and columns of data.",
  tabs: "Switches between panels of content.",
  textarea: "A multi-line text field.",
  toast: "A brief notification layered over the page.",
  toggle: "A button that stays pressed.",
  "toggle-group": "A set of toggles, single or multiple choice.",
  tooltip: "A short label that appears on hover or focus.",
}
