import type { ArtProps } from "../props"

// Ported from business.x.com: resources/x-marketing-calendar.
export function Tracks({
  variant = "wide",
  ...props
}: ArtProps & { variant?: "wide" | "narrow" }) {
  if (variant === "wide")
    return (
      <svg
        fill="none"
        preserveAspectRatio="xMidYMid slice"
        shapeRendering="geometricPrecision"
        viewBox="0 0 1118 462"
        aria-hidden="true"
        {...props}
      >
        <g data-group="rails">
          <line
            stroke="currentColor"
            x1="0"
            y1="95"
            y2="95"
            strokeWidth="1"
            vectorEffect="non-scaling-stroke"
            x2="1118"
          />
          <line
            stroke="currentColor"
            x1="1118"
            y1="232.08"
            y2="232.08"
            strokeWidth="1"
            vectorEffect="non-scaling-stroke"
            x2="0"
          />
          <line
            stroke="currentColor"
            x1="0"
            y1="370.19"
            y2="370.19"
            strokeWidth="1"
            vectorEffect="non-scaling-stroke"
            x2="1118"
          />
        </g>
        <g data-group="marks">
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="7"
              stroke="currentColor"
              width="39"
              x="170.5"
              y="91.5"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="7"
                stroke="currentColor"
                width="39"
                x="170.5"
                y="91.5"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="327.66"
              cy="95"
              fill="var(--ds-background-100)"
              r="9.5"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="327.66"
                cy="95"
                fill="currentColor"
                r="9.5"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="7"
              stroke="currentColor"
              width="7"
              x="493.5"
              y="91.5"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="7"
                stroke="currentColor"
                width="7"
                x="493.5"
                y="91.5"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="7"
              stroke="currentColor"
              width="39"
              x="509.5"
              y="91.5"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="7"
                stroke="currentColor"
                width="39"
                x="509.5"
                y="91.5"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="608.96"
              cy="95"
              fill="var(--ds-background-100)"
              r="9.5"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <circle cx="608.96" cy="95" fill="currentColor" r="1.5" />
            <g opacity="0">
              <circle
                cx="608.96"
                cy="95"
                fill="currentColor"
                r="9.5"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
              <circle cx="608.96" cy="95" fill="var(--ds-gray-100)" r="1.5" />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="currentColor"
              height="7"
              stroke="currentColor"
              width="7"
              x="716.01"
              y="91.5"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="var(--ds-background-100)"
                height="7"
                stroke="currentColor"
                width="7"
                x="716.01"
                y="91.5"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="87"
              stroke="currentColor"
              width="95"
              x="773.91"
              y="51.5"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="773.5"
              cy="95"
              fill="var(--ds-background-100)"
              r="9.5"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="773.5"
                cy="95"
                fill="currentColor"
                r="9.5"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="currentColor"
              height="9"
              stroke="currentColor"
              width="9"
              x="864.5"
              y="90.5"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="var(--ds-background-100)"
                height="9"
                stroke="currentColor"
                width="9"
                x="864.5"
                y="90.5"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="927.5"
              cy="95"
              fill="var(--ds-background-100)"
              r="9.5"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <circle cx="927.5" cy="95" fill="currentColor" r="1.5" />
            <g opacity="0">
              <circle
                cx="927.5"
                cy="95"
                fill="currentColor"
                r="9.5"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
              <circle cx="927.5" cy="95" fill="var(--ds-gray-100)" r="1.5" />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="267.64"
              cy="232.08"
              fill="var(--ds-background-100)"
              r="9.5"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="267.64"
                cy="232.08"
                fill="currentColor"
                r="9.5"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="7"
              stroke="currentColor"
              width="7"
              x="350.65"
              y="228.58"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="7"
                stroke="currentColor"
                width="7"
                x="350.65"
                y="228.58"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="23"
              stroke="currentColor"
              width="23"
              x="427.17"
              y="220.58"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="23"
                stroke="currentColor"
                width="23"
                x="427.17"
                y="220.58"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="23"
              stroke="currentColor"
              width="23"
              x="667.83"
              y="220.58"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="23"
                stroke="currentColor"
                width="23"
                x="667.83"
                y="220.58"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="currentColor"
              height="7"
              stroke="currentColor"
              width="7"
              x="760.33"
              y="228.58"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="var(--ds-background-100)"
                height="7"
                stroke="currentColor"
                width="7"
                x="760.33"
                y="228.58"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="846.35"
              cy="232.08"
              fill="var(--ds-background-100)"
              r="9.5"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="846.35"
                cy="232.08"
                fill="currentColor"
                r="9.5"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="162"
              cy="370.19"
              fill="var(--ds-background-100)"
              r="9.5"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <circle cx="162" cy="370.19" fill="currentColor" r="1.5" />
            <g opacity="0">
              <circle
                cx="162"
                cy="370.19"
                fill="currentColor"
                r="9.5"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
              <circle cx="162" cy="370.19" fill="var(--ds-gray-100)" r="1.5" />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="87"
              stroke="currentColor"
              width="95"
              x="221.08999999999997"
              y="326.69"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="currentColor"
              height="9"
              stroke="currentColor"
              width="9"
              x="216.5"
              y="365.69"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="var(--ds-background-100)"
                height="9"
                stroke="currentColor"
                width="9"
                x="216.5"
                y="365.69"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="316"
              cy="370.19"
              fill="var(--ds-background-100)"
              r="9.5"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="316"
                cy="370.19"
                fill="currentColor"
                r="9.5"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="currentColor"
              height="7"
              stroke="currentColor"
              width="7"
              x="367"
              y="366.69"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="var(--ds-background-100)"
                height="7"
                stroke="currentColor"
                width="7"
                x="367"
                y="366.69"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="481"
              cy="370.19"
              fill="var(--ds-background-100)"
              r="9.5"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <circle cx="481" cy="370.19" fill="currentColor" r="1.5" />
            <g opacity="0">
              <circle
                cx="481"
                cy="370.19"
                fill="currentColor"
                r="9.5"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
              <circle cx="481" cy="370.19" fill="var(--ds-gray-100)" r="1.5" />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="7"
              stroke="currentColor"
              width="39"
              x="541.5"
              y="366.69"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="7"
                stroke="currentColor"
                width="39"
                x="541.5"
                y="366.69"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="7"
              stroke="currentColor"
              width="7"
              x="589.5"
              y="366.69"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="7"
                stroke="currentColor"
                width="7"
                x="589.5"
                y="366.69"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="761.84"
              cy="370.19"
              fill="var(--ds-background-100)"
              r="9.5"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="761.84"
                cy="370.19"
                fill="currentColor"
                r="9.5"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="7"
              stroke="currentColor"
              width="39"
              x="880.5"
              y="366.69"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="7"
                stroke="currentColor"
                width="39"
                x="880.5"
                y="366.69"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
        </g>
        <g
          data-part="disc"
          style={{
            transformBox: "view-box",
            transformOrigin: "559px 232.08px 0",
          }}
        >
          <g style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}>
            <circle
              cx="559"
              cy="232.08"
              fill="currentColor"
              r="34.5"
              stroke="var(--ds-gray-100)"
              strokeWidth="5"
            />
            <g>
              <path
                d="M545.011 217L555.871 233.052L545.739 245L549.266 245L557.438 235.359L563.957 245L572.843 245L562.376 229.527L573 217L569.473 217L560.808 227.221L553.89 217L545 217L545.011 217ZM565.118 242.749L549.222 219.251L552.735 219.251L568.635 242.749L565.121 242.749L565.118 242.749Z"
                fill="var(--ds-gray-100)"
                transform="translate(0 1.08) scale(1)"
              />
            </g>
          </g>
        </g>
      </svg>
    )
  if (variant === "narrow")
    return (
      <svg
        fill="none"
        preserveAspectRatio="xMidYMid slice"
        shapeRendering="geometricPrecision"
        viewBox="0 0 404 240"
        aria-hidden="true"
        {...props}
      >
        <g data-group="rails">
          <line
            stroke="currentColor"
            x1="0"
            y1="56"
            y2="56"
            strokeWidth="1"
            vectorEffect="non-scaling-stroke"
            x2="404"
          />
          <line
            stroke="currentColor"
            x1="404"
            y1="120"
            y2="120"
            strokeWidth="1"
            vectorEffect="non-scaling-stroke"
            x2="0"
          />
          <line
            stroke="currentColor"
            x1="0"
            y1="184"
            y2="184"
            strokeWidth="1"
            vectorEffect="non-scaling-stroke"
            x2="404"
          />
        </g>
        <g data-group="marks">
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="4.34"
              stroke="currentColor"
              width="24.18"
              x="49.91"
              y="53.83"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="4.34"
                stroke="currentColor"
                width="24.18"
                x="49.91"
                y="53.83"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="130"
              cy="56"
              fill="var(--ds-background-100)"
              r="5.89"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <circle cx="130" cy="56" fill="currentColor" r="0.93" />
            <g opacity="0">
              <circle
                cx="130"
                cy="56"
                fill="currentColor"
                r="5.89"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
              <circle cx="130" cy="56" fill="var(--ds-gray-100)" r="0.93" />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="currentColor"
              height="4.34"
              stroke="currentColor"
              width="4.34"
              x="193.83"
              y="53.83"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="var(--ds-background-100)"
                height="4.34"
                stroke="currentColor"
                width="4.34"
                x="193.83"
                y="53.83"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="53.94"
              stroke="currentColor"
              width="58.9"
              x="270.55"
              y="29.03"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="270.5"
              cy="56"
              fill="var(--ds-background-100)"
              r="5.89"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="270.5"
                cy="56"
                fill="currentColor"
                r="5.89"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="currentColor"
              height="5.58"
              stroke="currentColor"
              width="5.58"
              x="326.71"
              y="53.21"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="var(--ds-background-100)"
                height="5.58"
                stroke="currentColor"
                width="5.58"
                x="326.71"
                y="53.21"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="74"
              cy="120"
              fill="var(--ds-background-100)"
              r="5.89"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="74"
                cy="120"
                fill="currentColor"
                r="5.89"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="4.34"
              stroke="currentColor"
              width="4.34"
              x="125.83"
              y="117.83"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="4.34"
                stroke="currentColor"
                width="4.34"
                x="125.83"
                y="117.83"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="14.26"
              stroke="currentColor"
              width="14.26"
              x="150.87"
              y="112.87"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="14.26"
                stroke="currentColor"
                width="14.26"
                x="150.87"
                y="112.87"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="14.26"
              stroke="currentColor"
              width="14.26"
              x="238.87"
              y="112.87"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="14.26"
                stroke="currentColor"
                width="14.26"
                x="238.87"
                y="112.87"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="currentColor"
              height="4.34"
              stroke="currentColor"
              width="4.34"
              x="287.83"
              y="117.83"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="var(--ds-background-100)"
                height="4.34"
                stroke="currentColor"
                width="4.34"
                x="287.83"
                y="117.83"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="336"
              cy="120"
              fill="var(--ds-background-100)"
              r="5.89"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="336"
                cy="120"
                fill="currentColor"
                r="5.89"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="60"
              cy="184"
              fill="var(--ds-background-100)"
              r="5.89"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <circle cx="60" cy="184" fill="currentColor" r="0.93" />
            <g opacity="0">
              <circle
                cx="60"
                cy="184"
                fill="currentColor"
                r="5.89"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
              <circle cx="60" cy="184" fill="var(--ds-gray-100)" r="0.93" />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="53.94"
              stroke="currentColor"
              width="58.9"
              x="98.55"
              y="157.03"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="currentColor"
              height="5.58"
              stroke="currentColor"
              width="5.58"
              x="95.71"
              y="181.21"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="var(--ds-background-100)"
                height="5.58"
                stroke="currentColor"
                width="5.58"
                x="95.71"
                y="181.21"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="157.5"
              cy="184"
              fill="var(--ds-background-100)"
              r="5.89"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="157.5"
                cy="184"
                fill="currentColor"
                r="5.89"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="currentColor"
              height="4.34"
              stroke="currentColor"
              width="4.34"
              x="193.83"
              y="181.83"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="var(--ds-background-100)"
                height="4.34"
                stroke="currentColor"
                width="4.34"
                x="193.83"
                y="181.83"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="4.34"
              stroke="currentColor"
              width="24.18"
              x="237.91"
              y="181.83"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="4.34"
                stroke="currentColor"
                width="24.18"
                x="237.91"
                y="181.83"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <rect
              fill="var(--ds-background-100)"
              height="4.34"
              stroke="currentColor"
              width="4.34"
              x="275.83"
              y="181.83"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <rect
                fill="currentColor"
                height="4.34"
                stroke="currentColor"
                width="4.34"
                x="275.83"
                y="181.83"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
          <g
            data-part="mark"
            style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}
          >
            <circle
              cx="344"
              cy="184"
              fill="var(--ds-background-100)"
              r="5.89"
              stroke="currentColor"
              strokeWidth="1"
              vectorEffect="non-scaling-stroke"
            />
            <g opacity="0">
              <circle
                cx="344"
                cy="184"
                fill="currentColor"
                r="5.89"
                stroke="currentColor"
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            </g>
          </g>
        </g>
        <g
          data-part="disc"
          style={{ transformBox: "view-box", transformOrigin: "202px 120px 0" }}
        >
          <g style={{ transformBox: "fill-box", transformOrigin: "50% 50%" }}>
            <circle
              cx="202"
              cy="120"
              fill="currentColor"
              r="21.39"
              stroke="var(--ds-gray-100)"
              strokeWidth="3.1"
            />
            <g>
              <path
                d="M545.011 217L555.871 233.052L545.739 245L549.266 245L557.438 235.359L563.957 245L572.843 245L562.376 229.527L573 217L569.473 217L560.808 227.221L553.89 217L545 217L545.011 217ZM565.118 242.749L549.222 219.251L552.735 219.251L568.635 242.749L565.121 242.749L565.118 242.749Z"
                fill="var(--ds-gray-100)"
                transform="translate(-144.58 -23.22) scale(0.62)"
              />
            </g>
          </g>
        </g>
      </svg>
    )
  return null
}
