// Named icon components for the docs examples.
//
// ziiz draws from @hugeicons, whose glyphs are data objects rendered through
// <HugeiconsIcon icon={...} />. Examples want a plain component per icon, so
// each glyph is wrapped once here and exported under a familiar name.
//
// Auto-generated by scripts/build-icons.ts. Do not edit by hand.
import * as React from "react"
import {
  Alert02Icon as Alert02Glyph,
  AlertCircleIcon as AlertCircleGlyph,
  AppWindowIcon as AppWindowGlyph,
  ArchiveIcon as ArchiveGlyph,
  ArrowLeft01Icon as ArrowLeft01Glyph,
  ArrowRight01Icon as ArrowRight01Glyph,
  ArrowUp01Icon as ArrowUp01Glyph,
  ArrowUpRight01Icon as ArrowUpRight01Glyph,
  AttachmentIcon as AttachmentGlyph,
  AudioLinesIcon as AudioLinesGlyph,
  AudioWaveformIcon as AudioWaveformGlyph,
  BadgeCheckIcon as BadgeCheckGlyph,
  BellIcon as BellGlyph,
  BluetoothIcon as BluetoothGlyph,
  BoldIcon as BoldGlyph,
  BookOpen01Icon as BookOpen01Glyph,
  BookOpenCheckIcon as BookOpenCheckGlyph,
  Bookmark01Icon as Bookmark01Glyph,
  BotIcon as BotGlyph,
  Building01Icon as Building01Glyph,
  CalculatorIcon as CalculatorGlyph,
  Calendar01Icon as Calendar01Glyph,
  CalendarPlusIcon as CalendarPlusGlyph,
  CheckIcon as CheckGlyph,
  CheckmarkCircle02Icon as CheckmarkCircle02Glyph,
  ChevronDownIcon as ChevronDownGlyph,
  ChevronLeftIcon as ChevronLeftGlyph,
  ChevronRightIcon as ChevronRightGlyph,
  CircleCheckIcon as CircleCheckGlyph,
  CircleDashedIcon as CircleDashedGlyph,
  CircleFadingArrowUpIcon as CircleFadingArrowUpGlyph,
  CircleFadingPlusIcon as CircleFadingPlusGlyph,
  ClipboardPasteIcon as ClipboardPasteGlyph,
  Clock01Icon as Clock01Glyph,
  CloudIcon as CloudGlyph,
  CodeIcon as CodeGlyph,
  CommandIcon as CommandGlyph,
  CopyIcon as CopyGlyph,
  CornerDownLeftIcon as CornerDownLeftGlyph,
  CreditCardIcon as CreditCardGlyph,
  Delete02Icon as Delete02Glyph,
  DotIcon as DotGlyph,
  Download01Icon as Download01Glyph,
  ExternalLinkIcon as ExternalLinkGlyph,
  EyeIcon as EyeGlyph,
  EyeOffIcon as EyeOffGlyph,
  File01Icon as File01Glyph,
  File02Icon as File02Glyph,
  FileBlockIcon as FileBlockGlyph,
  FileCodeIcon as FileCodeGlyph,
  FileSearchIcon as FileSearchGlyph,
  Folder01Icon as Folder01Glyph,
  FolderAddIcon as FolderAddGlyph,
  FolderCodeIcon as FolderCodeGlyph,
  FolderOpenIcon as FolderOpenGlyph,
  FolderSearchIcon as FolderSearchGlyph,
  Forward01Icon as Forward01Glyph,
  FrameIcon as FrameGlyph,
  GalleryVerticalEndIcon as GalleryVerticalEndGlyph,
  GitBranchIcon as GitBranchGlyph,
  GitForkIcon as GitForkGlyph,
  GlobeIcon as GlobeGlyph,
  HelpCircleIcon as HelpCircleGlyph,
  Home01Icon as Home01Glyph,
  Image01Icon as Image01Glyph,
  InboxIcon as InboxGlyph,
  InformationCircleIcon as InformationCircleGlyph,
  JavaScriptIcon as JavaScriptGlyph,
  KeyboardIcon as KeyboardGlyph,
  LanguageSkillIcon as LanguageSkillGlyph,
  Layout01Icon as Layout01Glyph,
  LayoutGridIcon as LayoutGridGlyph,
  ListChevronsDownUpIcon as ListChevronsDownUpGlyph,
  ListFilterPlusIcon as ListFilterPlusGlyph,
  LoaderPinwheelIcon as LoaderPinwheelGlyph,
  Logout01Icon as Logout01Glyph,
  Mail01Icon as Mail01Glyph,
  MailValidation01Icon as MailValidation01Glyph,
  MapingIcon as MapingGlyph,
  Maximize01Icon as Maximize01Glyph,
  Message01Icon as Message01Glyph,
  MessageSquareCodeIcon as MessageSquareCodeGlyph,
  Minimize01Icon as Minimize01Glyph,
  MinusSignCircleIcon as MinusSignCircleGlyph,
  MonitorDotIcon as MonitorDotGlyph,
  MoonIcon as MoonGlyph,
  MoreHorizontalIcon as MoreHorizontalGlyph,
  PaintBoardIcon as PaintBoardGlyph,
  PencilIcon as PencilGlyph,
  PieChartIcon as PieChartGlyph,
  PlusMinusIcon as PlusMinusGlyph,
  RefreshCwOffIcon as RefreshCwOffGlyph,
  RefreshIcon as RefreshGlyph,
  RotateCcwSquareIcon as RotateCcwSquareGlyph,
  RotateCwSquareIcon as RotateCwSquareGlyph,
  SaveIcon as SaveGlyph,
  ScissorIcon as ScissorGlyph,
  Search01Icon as Search01Glyph,
  SecurityWarningIcon as SecurityWarningGlyph,
  Settings01Icon as Settings01Glyph,
  Share01Icon as Share01Glyph,
  Shield01Icon as Shield01Glyph,
  SmileIcon as SmileGlyph,
  SparklesIcon as SparklesGlyph,
  StarIcon as StarGlyph,
  Sun01Icon as Sun01Glyph,
  TableIcon as TableGlyph,
  Tag01Icon as Tag01Glyph,
  Telescope01Icon as Telescope01Glyph,
  TerminalIcon as TerminalGlyph,
  TextItalicIcon as TextItalicGlyph,
  TextUnderlineIcon as TextUnderlineGlyph,
  ThumbsDownIcon as ThumbsDownGlyph,
  ThumbsUpIcon as ThumbsUpGlyph,
  UnfoldMoreIcon as UnfoldMoreGlyph,
  UserIcon as UserGlyph,
  UserRemove01Icon as UserRemove01Glyph,
  VolumeOffIcon as VolumeOffGlyph,
  Wallet01Icon as Wallet01Glyph,
  XingIcon as XingGlyph,
  ZoomInAreaIcon as ZoomInAreaGlyph,
  ZoomOutAreaIcon as ZoomOutAreaGlyph,
} from "@hugeicons/core-free-icons"
import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react"

// Examples treat an icon as a plain <svg>, which is what they were written
// against. HugeiconsIcon narrows strokeWidth to a number, so it is coerced
// here rather than leaking that constraint into every call site.
export type IconProps = React.ComponentProps<"svg">

export type IconComponent = React.ComponentType<IconProps>

function icon(glyph: IconSvgElement) {
  function Icon({ strokeWidth = 2, ...props }: IconProps) {
    return (
      <HugeiconsIcon
        icon={glyph}
        strokeWidth={Number(strokeWidth)}
        {...props}
      />
    )
  }
  return Icon
}

export const AlertCircleIcon = icon(AlertCircleGlyph)
export const AlertTriangleIcon = icon(Alert02Glyph)
export const AppWindowIcon = icon(AppWindowGlyph)
export const ArchiveIcon = icon(ArchiveGlyph)
export const ArrowLeftIcon = icon(ArrowLeft01Glyph)
export const ArrowRightIcon = icon(ArrowRight01Glyph)
export const ArrowUpIcon = icon(ArrowUp01Glyph)
export const ArrowUpRightIcon = icon(ArrowUpRight01Glyph)
export const AudioLinesIcon = icon(AudioLinesGlyph)
export const AudioWaveform = icon(AudioWaveformGlyph)
export const BadgeCheck = icon(BadgeCheckGlyph)
export const BadgeCheckIcon = icon(BadgeCheckGlyph)
export const Bell = icon(BellGlyph)
export const BellIcon = icon(BellGlyph)
export const BluetoothIcon = icon(BluetoothGlyph)
export const Bold = icon(BoldGlyph)
export const BoldIcon = icon(BoldGlyph)
export const BookmarkIcon = icon(Bookmark01Glyph)
export const BookOpen = icon(BookOpen01Glyph)
export const BookOpenCheck = icon(BookOpenCheckGlyph)
export const Bot = icon(BotGlyph)
export const BotIcon = icon(BotGlyph)
export const Building2Icon = icon(Building01Glyph)
export const Calculator = icon(CalculatorGlyph)
export const CalculatorIcon = icon(CalculatorGlyph)
export const Calendar = icon(Calendar01Glyph)
export const CalendarIcon = icon(Calendar01Glyph)
export const CalendarPlusIcon = icon(CalendarPlusGlyph)
export const CheckCircle2Icon = icon(CheckmarkCircle02Glyph)
export const CheckIcon = icon(CheckGlyph)
export const ChevronDownIcon = icon(ChevronDownGlyph)
export const ChevronLeftIcon = icon(ChevronLeftGlyph)
export const ChevronRight = icon(ChevronRightGlyph)
export const ChevronRightIcon = icon(ChevronRightGlyph)
export const ChevronsUpDown = icon(UnfoldMoreGlyph)
export const CircleAlertIcon = icon(AlertCircleGlyph)
export const CircleCheckIcon = icon(CircleCheckGlyph)
export const CircleDashedIcon = icon(CircleDashedGlyph)
export const CircleFadingArrowUpIcon = icon(CircleFadingArrowUpGlyph)
export const CircleFadingPlusIcon = icon(CircleFadingPlusGlyph)
export const ClipboardPasteIcon = icon(ClipboardPasteGlyph)
export const Clock2Icon = icon(Clock01Glyph)
export const ClockIcon = icon(Clock01Glyph)
export const CodeIcon = icon(CodeGlyph)
export const Command = icon(CommandGlyph)
export const CopyIcon = icon(CopyGlyph)
export const CreditCard = icon(CreditCardGlyph)
export const CreditCardIcon = icon(CreditCardGlyph)
export const DotIcon = icon(DotGlyph)
export const DownloadIcon = icon(Download01Glyph)
export const ExternalLinkIcon = icon(ExternalLinkGlyph)
export const EyeIcon = icon(EyeGlyph)
export const EyeOffIcon = icon(EyeOffGlyph)
export const FileCodeIcon = icon(FileCodeGlyph)
export const FileIcon = icon(File01Glyph)
export const FileSearchIcon = icon(FileSearchGlyph)
export const FileTextIcon = icon(File02Glyph)
export const FileWarningIcon = icon(FileBlockGlyph)
export const Folder = icon(Folder01Glyph)
export const FolderIcon = icon(Folder01Glyph)
export const FolderOpenIcon = icon(FolderOpenGlyph)
export const FolderPlusIcon = icon(FolderAddGlyph)
export const FolderSearchIcon = icon(FolderSearchGlyph)
export const Forward = icon(Forward01Glyph)
export const Frame = icon(FrameGlyph)
export const GalleryVerticalEnd = icon(GalleryVerticalEndGlyph)
export const GitBranchIcon = icon(GitBranchGlyph)
export const GlobeIcon = icon(GlobeGlyph)
export const HelpCircleIcon = icon(HelpCircleGlyph)
export const HomeIcon = icon(Home01Glyph)
export const IconBell = icon(BellGlyph)
export const IconBrandJavascript = icon(JavaScriptGlyph)
export const IconCheck = icon(CheckGlyph)
export const IconCloud = icon(CloudGlyph)
export const IconCopy = icon(CopyGlyph)
export const IconCornerDownLeft = icon(CornerDownLeftGlyph)
export const IconFolderCode = icon(FolderCodeGlyph)
export const IconGitBranch = icon(GitBranchGlyph)
export const IconGitFork = icon(GitForkGlyph)
export const IconInfoCircle = icon(InformationCircleGlyph)
export const IconPlus = icon(PlusMinusGlyph)
export const IconRefresh = icon(RefreshGlyph)
export const IconStar = icon(StarGlyph)
export const ImageIcon = icon(Image01Glyph)
export const InboxIcon = icon(InboxGlyph)
export const InfoIcon = icon(InformationCircleGlyph)
export const Italic = icon(TextItalicGlyph)
export const ItalicIcon = icon(TextItalicGlyph)
export const KeyboardIcon = icon(KeyboardGlyph)
export const LanguagesIcon = icon(LanguageSkillGlyph)
export const LayoutGridIcon = icon(LayoutGridGlyph)
export const LayoutIcon = icon(Layout01Glyph)
export const ListFilterIcon = icon(ListFilterPlusGlyph)
export const ListIcon = icon(ListChevronsDownUpGlyph)
export const LoaderIcon = icon(LoaderPinwheelGlyph)
export const LogOut = icon(Logout01Glyph)
export const LogOutIcon = icon(Logout01Glyph)
export const MailCheckIcon = icon(MailValidation01Glyph)
export const MailIcon = icon(Mail01Glyph)
export const Map = icon(MapingGlyph)
export const MaximizeIcon = icon(Maximize01Glyph)
export const MessageCircleDashedIcon = icon(Message01Glyph)
export const MessageSquareIcon = icon(MessageSquareCodeGlyph)
export const MinimizeIcon = icon(Minimize01Glyph)
export const MinusIcon = icon(MinusSignCircleGlyph)
export const MonitorIcon = icon(MonitorDotGlyph)
export const MoonIcon = icon(MoonGlyph)
export const MoreHorizontal = icon(MoreHorizontalGlyph)
export const MoreHorizontalIcon = icon(MoreHorizontalGlyph)
export const PaletteIcon = icon(PaintBoardGlyph)
export const PaperclipIcon = icon(AttachmentGlyph)
export const PencilIcon = icon(PencilGlyph)
export const PieChart = icon(PieChartGlyph)
export const Plus = icon(PlusMinusGlyph)
export const PlusIcon = icon(PlusMinusGlyph)
export const RefreshCcwIcon = icon(RefreshGlyph)
export const RefreshCwIcon = icon(RefreshCwOffGlyph)
export const RotateCcwIcon = icon(RotateCcwSquareGlyph)
export const RotateCwIcon = icon(RotateCwSquareGlyph)
export const SaveIcon = icon(SaveGlyph)
export const ScissorsIcon = icon(ScissorGlyph)
export const Search = icon(Search01Glyph)
export const SearchIcon = icon(Search01Glyph)
export const Settings = icon(Settings01Glyph)
export const Settings2 = icon(Settings01Glyph)
export const SettingsIcon = icon(Settings01Glyph)
export const ShareIcon = icon(Share01Glyph)
export const ShieldAlertIcon = icon(SecurityWarningGlyph)
export const ShieldIcon = icon(Shield01Glyph)
export const Smile = icon(SmileGlyph)
export const SmileIcon = icon(SmileGlyph)
export const Sparkles = icon(SparklesGlyph)
export const SquareTerminal = icon(TerminalGlyph)
export const StarIcon = icon(StarGlyph)
export const SunIcon = icon(Sun01Glyph)
export const TableIcon = icon(TableGlyph)
export const TagIcon = icon(Tag01Glyph)
export const TelescopeIcon = icon(Telescope01Glyph)
export const ThumbsDownIcon = icon(ThumbsDownGlyph)
export const ThumbsUpIcon = icon(ThumbsUpGlyph)
export const Trash2 = icon(Delete02Glyph)
export const Trash2Icon = icon(Delete02Glyph)
export const TrashIcon = icon(Delete02Glyph)
export const Underline = icon(TextUnderlineGlyph)
export const UnderlineIcon = icon(TextUnderlineGlyph)
export const User = icon(UserGlyph)
export const UserIcon = icon(UserGlyph)
export const UserRoundXIcon = icon(UserRemove01Glyph)
export const VolumeOffIcon = icon(VolumeOffGlyph)
export const WalletIcon = icon(Wallet01Glyph)
export const XIcon = icon(XingGlyph)
export const ZoomInIcon = icon(ZoomInAreaGlyph)
export const ZoomOutIcon = icon(ZoomOutAreaGlyph)
